#!/usr/bin/env python3
"""Generate the parts of the documentation which describe what this integration supports.

A list of supported devices and EEPs rots the moment it is typed out by hand: a device added
to `device_catalog.py`, an EEP added to a platform schema or a profile added to `eltakobus`
would silently stay missing from the readme. So those lists are not written, they are rendered
from the same source the help page of the web ui uses (`help_catalog.build_catalog()`).

Generated by this script:

* `docs/supported-devices.md`               - the complete reference (devices, EEPs, platforms)
* the marked block in `README.md`           - the compact summary of it
* `custom_components/eltako/docs_index.json` - the documentation index shipped to HACS installs

Usage:

    python generate_docs.py            # write the files
    python generate_docs.py --check    # fail if they are not up to date (used by the tests)

Everything outside of the markers stays untouched - the prose of the readme is written by hand
on purpose, only the lists are generated.
"""

from __future__ import annotations

import argparse
import os
import posixpath
import sys

REPOSITORY_ROOT = os.path.dirname(os.path.abspath(__file__))
REPOSITORY_URL = 'https://github.com/grimmpp/home-assistant-eltako'
# Absolute base for the catalog payload only: the help page of the web ui renders inside Home
# Assistant, where a relative link would point into the Home Assistant frontend. Links between
# the generated markdown files are relative instead - see link().
DOC_BASE_URL = f'{REPOSITORY_URL}/tree/main'

# paths relative to the repository root - links between the generated files are built from
# them, see link()
SUPPORTED_DEVICES_DOC_PATH = 'docs/supported-devices.md'
README_PATH = 'README.md'

SUPPORTED_DEVICES_DOC = os.path.join(REPOSITORY_ROOT, *SUPPORTED_DEVICES_DOC_PATH.split('/'))
README = os.path.join(REPOSITORY_ROOT, README_PATH)

# The block of the readme which is rendered. Everything between the two markers is replaced,
# the markers themselves stay.
README_MARKER_START = '<!-- generated: supported devices and eeps - do not edit, run generate_docs.py -->'
README_MARKER_END = '<!-- /generated -->'

GENERATED_HINT_TEMPLATE = ('*This page is generated from the code by '
                           '[`generate_docs.py`]({generate_docs}) &ndash; do not edit it by hand.*')

# Documentation of a platform, keyed by the platform name. The schemas document themselves
# ("Voluptuous schema for Eltako lights."), which says nothing a reader does not already know.
PLATFORM_DESCRIPTIONS = {
    'binary_sensor': 'Contacts, rocker switches, occupancy and water sensors - everything with a state of on/off.',
    'climate': 'Heating and cooling: room thermostats and the actuators they control.',
    'cover': 'Blinds and shutters incl. travel times and tilt.',
    'fan': 'Ventilation fans with on/off or percentage speed control.',
    'light': 'Switchable and dimmable lights.',
    'sensor': 'Measured values: temperature, humidity, brightness, air quality, meter readings, weather.',
    'switch': 'Relays and everything else which is switched on and off.',
}

# Tutorials which explain a platform in depth. Derived from nothing - a doc does not state
# which platform it belongs to.
PLATFORM_DOCS = {
    'climate': 'docs/heating-and-cooling/readme.md',
    'cover': 'docs/relays-and-switches/readme.md',
    'light': 'docs/lights-tutorial/readme.md',
    'switch': 'docs/relays-and-switches/readme.md',
}


# --------------------------------------------------------------------------- helpers
def _cell(text) -> str:
    """A value inside a markdown table cell."""
    if text is None:
        return ''
    return str(text).replace('|', '\\|').replace('\n', ' ').strip()


def _code_list(values) -> str:
    return ', '.join(f'`{value}`' for value in values) if values else '&ndash;'


def link(target: str, from_file: str) -> str:
    """A link to a file of this repository, relative to the file it is written into.

    Relative and not `https://github.com/.../tree/main/...`: an absolute link always points at
    the state of `main`, so a document which was added on a branch is a 404 until it is merged,
    and a fork links back into this repository instead of into itself. Relative links follow
    whatever branch, fork or checkout they are read in - on github, in a pull request and in an
    editor alike. (The web ui needs absolute urls, it renders inside Home Assistant; those are
    built by help_catalog.py from REPOSITORY_URL.)

    `target` is relative to the repository root, `from_file` is the file being generated.
    """
    return posixpath.relpath(target, posixpath.dirname(from_file)) or '.'


def _platform_label(platform: str, from_file: str) -> str:
    label = platform.replace('_', ' ')
    doc = PLATFORM_DOCS.get(platform)
    return f'[{label}]({link(doc, from_file)})' if doc else label


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    lines = ['| ' + ' | '.join(header) + ' |',
             '| ' + ' | '.join('---' for _ in header) + ' |']
    lines += ['| ' + ' | '.join(_cell(value) for value in row) + ' |' for row in rows]
    return lines


# --------------------------------------------------------------------------- renderers
def render_platform_table(catalog: dict, from_file: str) -> list[str]:
    """Which platform accepts which EEP - the table a user needs to configure a device."""
    rows = []
    for platform in catalog['platforms']:
        name = platform['platform']
        rows.append([
            f"**{_platform_label(name, from_file)}**",
            PLATFORM_DESCRIPTIONS.get(name, platform.get('description', '')),
            _code_list(platform['eeps']),
            _code_list(platform['sender_eeps']),
        ])
    return _table(['Platform', 'What it covers', 'EEP of the device', 'Sender EEP (what Home Assistant sends)'],
                  rows)


def render_eep_table(catalog: dict) -> list[str]:
    """Every EEP, what it is and where it can be used."""
    rows = []
    for eep in catalog['eeps']:
        if eep['platforms'] or eep['sender_platforms']:
            usage = ', '.join(eep['platforms']) or '&ndash;'
            sender = ', '.join(eep['sender_platforms']) or '&ndash;'
        else:
            # decodable, recorded and analysable - but no platform turns it into an entity
            usage = sender = '*recording only*'
        rows.append([
            f"`{eep['eep']}`",
            eep['description'] or '',
            usage,
            sender,
            ', '.join(eep['devices']) or '&ndash;',
        ])
    return _table(['EEP', 'What it is', 'Entity platform', 'Usable as sender for', 'Devices'], rows)


def render_device_table(catalog: dict) -> list[str]:
    """The device catalog: one row per hardware type.

    The platform is not linked here - with one link per row the table becomes unreadable in
    the raw markdown. The tutorials are linked in the platform table above.
    """
    rows = []
    for device in catalog['devices']:
        if device['is_gateway']:
            continue                      # gateways have their own table in the readme
        profiles = device['profiles']
        # a device without a profile is known to the bus scan (it is recognized and named) but
        # has nothing to expose - a clock module or a gateway of the rack
        platforms = ', '.join(device['platforms']) or '*detected only*'
        rows.append([
            f"**{device['hw_type']}**",
            device['brand'],
            device['description'],
            'RS485 bus' if device['bus_device'] else 'wireless',
            device['address_count'] or '',
            platforms,
            _code_list(sorted({profile['eep'] for profile in profiles if profile['eep']})),
            _code_list(sorted({profile['sender_eep'] for profile in profiles if profile['sender_eep']})),
        ])
    return _table(['Device', 'Brand', 'What it is', 'Connection', 'Addresses', 'Platform', 'EEP', 'Sender EEP'],
                  rows)


def render_supported_devices_page(catalog: dict) -> str:
    """The complete generated reference page."""
    summary = catalog['summary']
    devices = [device for device in catalog['devices'] if not device['is_gateway']]

    lines = [
        '# Supported devices and EEPs',
        '',
        GENERATED_HINT_TEMPLATE.format(
            generate_docs=link('generate_docs.py', SUPPORTED_DEVICES_DOC_PATH)),
        '',
        f"The integration knows **{len(devices)} device types** and **{summary['eep_count']} EnOcean "
        f"Equipment Profiles**, of which **{summary['entity_eep_count']}** can become a Home Assistant "
        f"entity on one of **{summary['platform_count']} platforms**. It is not limited to ELTAKO "
        'hardware - any device which speaks one of these profiles works.',
        '',
        'The **Help** page of the web ui shows the same lists for the version you actually run.',
        '',
        '## Platforms',
        '',
        'A device is configured for the platform which matches what it does. The platform decides which',
        'EEPs are accepted - anything else is rejected by the configuration check.',
        '',
    ]
    lines += render_platform_table(catalog, SUPPORTED_DEVICES_DOC_PATH)
    lines += [
        '',
        '## Devices',
        '',
        'Hardware types the integration knows by name. Selecting one in the device form of the web ui',
        'prefills its EEP, sender EEP and platform, and *addresses* is how many bus addresses a device',
        'occupies (a four channel actuator takes four). Devices which are not listed here still work as',
        'long as they speak one of the profiles below.',
        '',
    ]
    lines += render_device_table(catalog)
    lines += [
        '',
        '## EnOcean Equipment Profiles (EEP)',
        '',
        'The profile decides how the payload of a telegram is interpreted. *Recording only* means the',
        'telegram is decoded, logged and can be analysed, but no platform turns it into an entity yet.',
        '',
    ]
    lines += render_eep_table(catalog)
    lines += [
        '',
        '## Gateways',
        '',
        f'See [the readme]({link("README.md", SUPPORTED_DEVICES_DOC_PATH)}#supported-gateways) and',
        f'[docs/gateways]({link("docs/gateways/readme.md", SUPPORTED_DEVICES_DOC_PATH)}).',
        '',
    ]
    return '\n'.join(lines) + '\n'


def render_readme_section(catalog: dict) -> str:
    """The compact block of the readme: the matrix plus the lists folded away."""
    summary = catalog['summary']
    devices = [device for device in catalog['devices'] if not device['is_gateway']]

    lines = [
        f"**{len(devices)} device types** and **{summary['eep_count']} EnOcean Equipment Profiles** are "
        f"supported, **{summary['entity_eep_count']}** of them can become a Home Assistant entity. "
        'The lists below are generated from the code, so they describe exactly this version &ndash; the '
        '**Help** page of the web ui shows the same for the version you run.',
        '',
    ]
    lines += render_platform_table(catalog, README_PATH)
    lines += [
        '',
        '<details>',
        f"<summary><b>All {len(devices)} devices</b> &ndash; the hardware types the integration knows by name</summary>",
        '',
    ]
    lines += render_device_table(catalog)
    lines += [
        '',
        '</details>',
        '',
        '<details>',
        f"<summary><b>All {summary['eep_count']} EEPs</b> &ndash; what they are and where they can be used</summary>",
        '',
    ]
    lines += render_eep_table(catalog)
    lines += [
        '',
        '</details>',
        '',
        f'Full reference: [{SUPPORTED_DEVICES_DOC_PATH}]'
        f'({link(SUPPORTED_DEVICES_DOC_PATH, README_PATH)}).',
    ]
    return '\n'.join(lines)


def render_readme(catalog: dict, current: str) -> str:
    """The readme with its generated block replaced."""
    start = current.find(README_MARKER_START)
    end = current.find(README_MARKER_END)
    if start < 0 or end < 0 or end < start:
        raise RuntimeError(
            f'The markers {README_MARKER_START} / {README_MARKER_END} are missing in README.md - '
            'without them there is nothing to replace.')

    head = current[:start + len(README_MARKER_START)]
    tail = current[end:]
    return f'{head}\n\n{render_readme_section(catalog)}\n\n{tail}'


# --------------------------------------------------------------------------- files
def _read(path: str) -> str:
    with open(path, encoding='utf-8') as handle:
        return handle.read()


def _write(path: str, content: str, check: bool) -> bool:
    """Write the file. Returns True when it changed (or would change, in check mode)."""
    current = _read(path) if os.path.exists(path) else None
    if current == content:
        return False
    if not check:
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write(content)
    return True


def generate(check: bool = False) -> list[str]:
    """Render everything. Returns the files which are out of date (or were written)."""
    # imported here so `--help` works without Home Assistant being installed
    from custom_components.eltako.catalog import help_catalog

    catalog = help_catalog.build_catalog(DOC_BASE_URL)
    outdated = []

    if _write(SUPPORTED_DEVICES_DOC, render_supported_devices_page(catalog), check):
        outdated.append(os.path.relpath(SUPPORTED_DEVICES_DOC, REPOSITORY_ROOT))

    if _write(README, render_readme(catalog, _read(README)), check):
        outdated.append(os.path.relpath(README, REPOSITORY_ROOT))

    # The index of the documentation ships with the integration (HACS installs only
    # custom_components/eltako/), so regenerate it here as well - one command for everything
    # which is generated. In check mode it is left alone: test_help_catalog.py compares it
    # against a fresh scan already, and writing a file would defeat the purpose of --check.
    if not check:
        before = _read(help_catalog.DOCS_INDEX_FILE) if os.path.exists(help_catalog.DOCS_INDEX_FILE) else None
        index = help_catalog.write_documentation_index()
        if _read(index) != before:
            outdated.append(os.path.relpath(index, REPOSITORY_ROOT))

    return outdated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true',
                        help='do not write anything, exit with 1 if a generated file is out of date')
    arguments = parser.parse_args()

    outdated = generate(check=arguments.check)

    if arguments.check:
        if outdated:
            print('Out of date, run "python generate_docs.py":')
            for path in outdated:
                print(f'  {path}')
            return 1
        print('The generated documentation is up to date.')
        return 0

    if outdated:
        for path in outdated:
            print(f'Wrote {path}')
    else:
        print('Nothing changed - the generated documentation was already up to date.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
