"""Import gateway and device configurations from a file.

Three formats are supported - the format is detected from the content, the file
extension does not matter:

* **.eodm** - the project files of the EnOcean Device Manager
  (https://github.com/grimmpp/enocean-device-manager). The file is yaml with
  python object tags; it is parsed with a restricted loader which maps every
  python object to a plain dict - nothing is instantiated or executed.
* **.xml** - an export of the Eltako PCT14 tool: the FAM14 of the export becomes
  the gateway, its bus devices become devices and the senders taught into them
  become the wireless sensors and pushbuttons (see `pct14_to_config`).
* **yaml** - the `eltako:` section of a configuration.yaml (or just its content
  with a `gateway:` list), e.g. one generated by the EnOcean Device Manager.

The imported gateways and devices are stored like the ones created in the web
ui (gateway_config.py / device_config.py): they survive restarts, can be edited
or removed in the ui, and a declaration in configuration.yaml always wins.

Used by the websocket command `eltako/config/import` (button in the web ui) and
by the `--demo` flag of the standalone runtime.
"""

from __future__ import annotations

import voluptuous as vol
import yaml

from homeassistant.const import CONF_DEVICE_CLASS, CONF_DEVICES, CONF_ID, CONF_NAME
from homeassistant.core import HomeAssistant
from homeassistant.components import websocket_api

from ..const import *
from . import config_helpers
from . import device_config
from ..catalog import device_catalog
from . import gateway_config

LOG_PREFIX_IMPORT = "Config Import"

WS_CONFIG_IMPORT: str = "eltako/config/import"

# platforms a device of an import may use (same set the web ui offers)
_SUPPORTED_PLATFORMS = set(device_config.SUPPORTED_PLATFORMS.keys())

# device_type fragments of the EnOcean Device Manager -> gateway type of this integration.
# Order matters: 'fam-usb' must match before 'fam14'.
_GATEWAY_TYPE_PATTERNS = [
    ("fam-usb", GatewayDeviceType.GatewayEltakoFAMUSB.value),
    ("fam usb", GatewayDeviceType.GatewayEltakoFAMUSB.value),
    ("fgw14", GatewayDeviceType.GatewayEltakoFGW14USB.value),
    ("fam14", GatewayDeviceType.GatewayEltakoFAM14.value),
    ("usb300", GatewayDeviceType.EnOceanUSB300.value),
    ("esp3", GatewayDeviceType.ESP3.value),
    ("lan", GatewayDeviceType.LAN.value),
]

_WIRED_GATEWAY_TYPES = {GatewayDeviceType.GatewayEltakoFAM14.value,
                        GatewayDeviceType.GatewayEltakoFGW14USB.value}

# sender ids of bus gateways are counted from this offset (see the
# HomeAssistantConfigurationGenerator of the EnOcean Device Manager)
_LOCAL_SENDER_OFFSET = "00-00-B0-00"

# fields of an eodm device which never belong into the device config
_EODM_INTERNAL_FIELDS = {CONF_COMMENT, CONF_REGISTERED_IN}


### ---------------------------------------------------------------------------
### restricted yaml loader for .eodm files
### ---------------------------------------------------------------------------

class _EodmLoader(yaml.SafeLoader):
    """SafeLoader which flattens the python object tags of an .eodm file.

    !!python/object:...            -> plain dict of the attributes
    !!python/name:x.y.Z            -> the dotted name as string
    !!python/object/apply:builtins.getattr [obj, 'NAME'] -> 'NAME' (enum member name)
    """


def _load_object_as_dict(loader, suffix, node):
    return loader.construct_mapping(node, deep=True)


def _load_name_as_string(loader, suffix, node):
    return suffix


def _load_apply(loader, suffix, node):
    if isinstance(node, yaml.SequenceNode):
        args = loader.construct_sequence(node, deep=True)
    else:
        args = list(loader.construct_mapping(node, deep=True).values())
    if suffix == "builtins.getattr" and len(args) == 2:
        return str(args[1])
    return args[0] if args else None


_EodmLoader.add_multi_constructor("tag:yaml.org,2002:python/object:", _load_object_as_dict)
_EodmLoader.add_multi_constructor("tag:yaml.org,2002:python/object/new:", _load_object_as_dict)
_EodmLoader.add_multi_constructor("tag:yaml.org,2002:python/name:", _load_name_as_string)
_EodmLoader.add_multi_constructor("tag:yaml.org,2002:python/object/apply:", _load_apply)


def is_eodm(content: str) -> bool:
    return "!!python/object:eo_man" in content


def parse_eodm(content: str) -> dict:
    """Parse an .eodm file into plain dicts. Raises yaml.YAMLError."""
    return yaml.load(content, Loader=_EodmLoader) or {}


### ---------------------------------------------------------------------------
### conversion: eodm -> configuration of this integration
### ---------------------------------------------------------------------------

def _gateway_type_of_name(device_type: str | None) -> str | None:
    """Device name of another tool ('FAM14', 'FAM-USB 515') -> gateway type of this integration."""
    name = str(device_type or "").lower()
    for fragment, gateway_type in _GATEWAY_TYPE_PATTERNS:
        if fragment in name:
            return gateway_type
    return None


def _gateway_type_of(device: dict) -> str | None:
    return _gateway_type_of_name(device.get("device_type"))


def _normalize_eep(eep) -> str | None:
    if not eep:
        return None
    return str(eep).replace("_", "-").upper()


def _normalize_platform(platform) -> str | None:
    if platform is None:
        return None
    return str(platform).lower()


def _add_address_offset(offset: str, last_byte_source: str) -> str:
    """sender id of the eodm (e.g. 00-00-B0-05) -> offset + its last byte."""
    from eltakobus.util import AddressExpression, b2s

    offset_int = int.from_bytes(AddressExpression.parse(offset)[0], "big")
    last = int(str(last_byte_source).replace("-", "")[-2:], 16)
    return b2s((offset_int + last).to_bytes(4, "big"))


def _convert_device(device: dict, gateway: dict, warnings: list[str]) -> tuple[str, dict] | None:
    """One eodm device -> (platform, device config of this integration)."""
    platform = _normalize_platform(device.get("ha_platform"))
    if platform not in _SUPPORTED_PLATFORMS:
        if platform not in (None, "", "unknown"):
            warnings.append(f"{device.get('external_id')}: platform '{platform}' is not "
                            f"supported by the import - skipped.")
        return None

    wired = gateway.get(CONF_DEVICE_TYPE) in _WIRED_GATEWAY_TYPES
    same_bus = str(device.get("base_id") or "").upper() == str(gateway.get(CONF_BASE_ID) or "").upper()
    address = device.get("address") if (device.get("bus_device") and wired and same_bus) \
        else device.get("external_id")

    result = {
        CONF_ID: str(address),
        CONF_EEP: _normalize_eep(device.get("eep")),
        CONF_NAME: device.get("name") or "",
    }

    for key, value in (device.get("additional_fields") or {}).items():
        if key in _EODM_INTERNAL_FIELDS or value in (None, "", {}):
            continue
        if key == CONF_SENDER and isinstance(value, dict) and value.get(CONF_ID):
            offset = _LOCAL_SENDER_OFFSET if wired else str(gateway.get(CONF_BASE_ID))
            try:
                sender_id = _add_address_offset(offset, str(value[CONF_ID]))
            except Exception:  # noqa: BLE001 - keep the original value, validation reports it
                sender_id = str(value[CONF_ID])
            result[CONF_SENDER] = {CONF_ID: sender_id,
                                   CONF_EEP: _normalize_eep(value.get(CONF_EEP))}
        else:
            result[key] = value

    return platform, result


def eodm_to_config(data: dict) -> tuple[list[dict], list[str]]:
    """Application data of the EnOcean Device Manager -> gateway list (yaml structure).

    Returns (gateways incl. their CONF_DEVICES, warnings). Only devices marked
    with 'Export to HA' (use_in_ha) are considered - like the yaml export of the
    device manager.
    """
    warnings: list[str] = []
    devices = [d for d in (data.get("devices") or {}).values() if isinstance(d, dict)]

    gateway_devices = [d for d in devices if _gateway_type_of(d) and d.get("use_in_ha", True)]
    other_devices = [d for d in devices if not _gateway_type_of(d) and d.get("use_in_ha")]

    gateways: list[dict] = []
    for index, gw in enumerate(gateway_devices, start=1):
        gateways.append({
            CONF_ID: index,
            CONF_DEVICE_TYPE: _gateway_type_of(gw),
            CONF_BASE_ID: str(gw.get("base_id") or "00-00-00-00").upper(),
            CONF_NAME: gw.get("name") or "",
            CONF_DEVICES: {},
        })
    if not gateways:
        warnings.append("The file contains no gateway marked with 'Export to HA'.")
        return [], warnings

    wired = [g for g in gateways if g[CONF_DEVICE_TYPE] in _WIRED_GATEWAY_TYPES]
    wireless = [g for g in gateways if g[CONF_DEVICE_TYPE] not in _WIRED_GATEWAY_TYPES]

    for device in other_devices:
        # bus devices belong to the wired gateway of their bus, everything
        # wireless goes to the (first) transceiver - or the first gateway at all
        target = None
        if device.get("bus_device"):
            target = next((g for g in wired if str(device.get("base_id") or "").upper()
                           == g[CONF_BASE_ID]), None) or (wired[0] if wired else None)
        if target is None:
            target = (wireless[0] if not device.get("bus_device") and wireless else None) \
                or gateways[0]

        converted = _convert_device(device, target, warnings)
        if converted is None:
            continue
        platform, entry = converted
        target[CONF_DEVICES].setdefault(platform, []).append(entry)

    return gateways, warnings


### ---------------------------------------------------------------------------
### PCT14 export (xml of the Eltako pc tool)
### ---------------------------------------------------------------------------
###
### A PCT14 export describes exactly one bus:
###
###   <exchange>
###     <rootdevice>                       the FAM14 the pc tool was connected to
###       <name>FAM14</name>
###       <rootdevicedata><baseid>          its base id, one element per byte
###     <devices>
###       <device>                          one bus device (may occupy several addresses)
###         <name>FSR14-4x</name>           device name as printed on the housing
###         <header><address>               first bus address
###                 <addressrange>          number of addresses/channels it occupies
###         <channels><channel channelnumber=".." description=".."/>
###         <data><rangeofid><entry>        the senders taught into the device
###
### Everything the export does not know (EEP, home assistant platform, sender EEP) comes
### from the device catalog - the same knowledge the device form of the web ui offers.

# the two elements every PCT14 export starts with
_PCT14_MARKERS = ("<exchange", "<rootdevice")

# a PCT14 entry of a taught-in sender which this import turns into a device. 'ha_sender'
# (00-00-B*) is home assistant itself and 'unknown' cannot be configured meaningfully.
_PCT14_IMPORTED_SENDER_ROLES = {"button", "fts14em", "sensor", "weather_station"}

# defaults of the EnOcean Device Manager for a cover (there is no runtime in the export)
_PCT14_COVER_DEFAULTS = {CONF_DEVICE_CLASS: "shutter", CONF_TIME_CLOSES: 25, CONF_TIME_OPENS: 25}
_PCT14_CLIMATE_DEFAULTS = {CONF_MIN_TARGET_TEMPERATURE: 16, CONF_MAX_TARGET_TEMPERATURE: 25}


def is_pct14(content: str) -> bool:
    """True for an xml export of the Eltako PCT14 tool."""
    head = content[:4096].lower()
    return all(marker in head for marker in _PCT14_MARKERS)


def parse_pct14(content: str):
    """Parse a PCT14 export into its xml tree. Raises vol.Invalid on a broken file."""
    try:
        from defusedxml.ElementTree import fromstring     # ships with home assistant
    except ImportError:                                   # pragma: no cover - standalone runtime
        from xml.etree.ElementTree import fromstring

    try:
        root = fromstring(content)
    except Exception as e:  # noqa: BLE001 - every parser reports its own exception type
        raise vol.Invalid(f"The file is not readable xml: {e}") from e
    if root.tag != "exchange":
        raise vol.Invalid(f"No PCT14 export: expected an '<exchange>' root element, "
                          f"found '{root.tag}'.")
    return root


def _pct14_text(node, *path: str) -> str:
    """Text of a nested element, e.g. _pct14_text(device, 'header', 'address')."""
    for tag in path:
        if node is None:
            return ""
        node = node.find(tag)
    if node is None or node.text is None:
        return ""
    return node.text.strip()


def _pct14_int(node, *path: str, default: int = 0) -> int:
    try:
        return int(_pct14_text(node, *path))
    except ValueError:
        return default


def _pct14_address(value: int) -> str:
    """Bus address / EnOcean address as number -> '00-00-00-05'."""
    from eltakobus.util import b2s

    return b2s(int(value).to_bytes(4, "big"))


def _pct14_sender_address(value: int) -> str:
    """entry_id of a taught-in sender -> 'FE-DB-0A-1B'.

    PCT14 stores an EnOcean address as a little endian number.
    """
    from eltakobus.util import b2s

    return b2s(int(value).to_bytes(4, "little"))


def _pct14_base_id(rootdevice) -> str:
    """Base id of the FAM14 - the export stores it as one element per byte."""
    baseid = rootdevice.find("rootdevicedata/baseid") if rootdevice is not None else None
    if baseid is None:
        return "00-00-00-00"
    return "-".join(f"{_pct14_int(baseid, f'baseid_byte_{index}'):02X}" for index in range(4))


def _pct14_channel_comment(device, channel: int) -> str:
    """Description the user typed into PCT14 for one channel of a device."""
    for node in device.findall("channels/channel"):
        try:
            if int(node.get("channelnumber", 0)) == channel:
                return (node.get("description") or "").strip()
        except ValueError:
            continue
    return ""


def _pct14_device_name(hw_type: str, address: str, device_comment: str, channel_comment: str,
                       channel: int, channel_count: int) -> str:
    """Name of an imported device - the descriptions of PCT14 are what the user knows.

    Every channel gets its own name: only the description of the channel makes a
    multi-channel device distinguishable, so without it the channel number is appended
    (otherwise all four channels of an 'FSR14-4x - Light Kitchen' would be called alike).
    """
    labels = [label for label in (device_comment, channel_comment) if label]
    name = " - ".join([hw_type] + labels) if labels else f"{hw_type} - {address}"
    if channel_count > 1 and not channel_comment:
        name += f" ({channel}/{channel_count})"
    return name


def _pct14_taught_in_senders(device) -> list[dict]:
    """Senders taught into one bus device: [{'id', 'key_function', 'channel_mask'}]."""
    from eltakobus.device import KeyFunction

    senders = []
    for entry in device.findall("data/rangeofid/entry"):
        entry_id = _pct14_int(entry, "entry_id")
        if entry_id <= 0 or entry_id > 0xFFFFFFFF:
            continue
        key_function = _pct14_int(entry, "entry_function")
        try:
            key_function_name = KeyFunction(key_function).name
        except ValueError:
            key_function_name = str(key_function)
        senders.append({
            CONF_ID: _pct14_sender_address(entry_id),
            "key_function_name": key_function_name,
            "channel_mask": _pct14_int(entry, "entry_channel"),
        })
    return senders


def _pct14_bus_device(device, hw_type: str, entry: dict, address_int: int,
                      channel: int, channel_count: int) -> tuple[str, dict]:
    """One channel of a PCT14 bus device -> (platform, device config of this integration)."""
    address = _pct14_address(address_int)
    result = {
        CONF_ID: address,
        CONF_EEP: entry["eep"],
        CONF_NAME: _pct14_device_name(hw_type, address, _pct14_text(device, "description"),
                                      _pct14_channel_comment(device, channel),
                                      channel, channel_count),
    }

    # sender id of a bus device: the offset of the local senders + its bus address
    # (the same rule the EnOcean Device Manager writes into the actuators with PCT14)
    if entry.get("sender_eep") and 0 < address_int % 128:
        result[CONF_SENDER] = {CONF_ID: _add_address_offset(_LOCAL_SENDER_OFFSET,
                                                           f"{address_int % 128:02X}"),
                               CONF_EEP: entry["sender_eep"]}

    if entry["platform"] == Platform.COVER:
        result.update(_PCT14_COVER_DEFAULTS)
    elif entry["platform"] == Platform.CLIMATE:
        result.update(_PCT14_CLIMATE_DEFAULTS)

    return str(entry["platform"]), result


def pct14_to_config(content: str) -> tuple[list[dict], list[str]]:
    """PCT14 export -> gateway list (yaml structure) with all its devices.

    The FAM14 of the export is the gateway. Its bus devices become the actuators and
    meters, the senders taught into them become the wireless pushbuttons and sensors -
    the classification of a sender is the one the device page uses for a bus scan
    (bus_members.classify_taught_in_sensor).

    Bus devices whose type the device catalog does not know are reported as a warning and
    skipped - an EEP cannot be guessed. Bus gateways besides the FAM14 (an FGW14-USB or an
    FTD14 of the same rack) are listed as a warning as well: a PCT14 export describes one
    bus, so they would only duplicate the gateway of this file.
    """
    from ..observation.bus_members import BusMemberRegistry

    root = parse_pct14(content)
    warnings: list[str] = []

    rootdevice = root.find("rootdevice")
    if rootdevice is None:
        raise vol.Invalid("The PCT14 export contains no '<rootdevice>' - its bus gateway "
                          "(FAM14) is unknown.")
    base_id = _pct14_base_id(rootdevice)
    rootdevice_name = _pct14_text(rootdevice, "name") or "FAM14"
    gateway_type = _gateway_type_of_name(rootdevice_name) or GatewayDeviceType.GatewayEltakoFAM14.value
    gateway = {
        CONF_ID: 1,
        CONF_DEVICE_TYPE: gateway_type,
        CONF_BASE_ID: base_id,
        CONF_NAME: _pct14_text(rootdevice, "description") or f"{rootdevice_name} {base_id}",
        CONF_DEVICES: {},
    }

    # sender id -> its classification; a wall switch is usually taught into several
    # actuators and must be imported only once
    senders: dict[str, dict] = {}
    # every address the export occupies with a bus device - a taught-in sender with such an
    # address is the actuator itself (central function, feedback), not a device of its own
    bus_addresses: set[str] = {base_id}
    skipped_types: set[str] = set()
    other_gateways: set[str] = set()

    for device in root.findall("devices/device"):
        hw_type = _pct14_text(device, "name")
        address_int = _pct14_int(device, "header", "address")
        channel_count = max(_pct14_int(device, "header", "addressrange", default=1), 1)
        if not hw_type or address_int <= 0:
            continue

        for sender in _pct14_taught_in_senders(device):
            senders.setdefault(sender[CONF_ID], sender)
        addresses = [_pct14_address(address_int + channel - 1)
                     for channel in range(1, channel_count + 1)]
        bus_addresses.update(addresses)

        entry = device_catalog.find_hw_type(hw_type)
        if _gateway_type_of_name(hw_type) or entry.get("gateway_type"):
            other_gateways.add(hw_type)
            continue
        if not entry.get("platform") or not entry.get("eep"):
            skipped_types.add(hw_type)
            continue

        for channel in range(1, channel_count + 1):
            platform, config = _pct14_bus_device(device, hw_type, entry,
                                                 address_int + channel - 1,
                                                 channel, channel_count)
            gateway[CONF_DEVICES].setdefault(platform, []).append(config)

    for sender in senders.values():
        if sender[CONF_ID] in bus_addresses:
            continue
        classification = BusMemberRegistry.classify_taught_in_sensor(sender[CONF_ID],
                                                                    sender["key_function_name"])
        if classification.get("role") not in _PCT14_IMPORTED_SENDER_ROLES:
            continue
        platform = str(classification["suggested_platform"])
        name = classification.get("suggested_name") or "Sensor"
        gateway[CONF_DEVICES].setdefault(platform, []).append({
            CONF_ID: sender[CONF_ID],
            CONF_EEP: classification["suggested_eep"],
            CONF_NAME: f"{name} {sender[CONF_ID]}",
        })

    if skipped_types:
        warnings.append(f"The device catalog does not know these bus devices, they were "
                        f"skipped: {', '.join(sorted(skipped_types))}.")
    if other_gateways:
        warnings.append(f"A PCT14 export describes one bus - the further bus gateway(s) "
                        f"{', '.join(sorted(other_gateways))} of the export were skipped, "
                        f"the FAM14 of the file is the gateway of this import.")
    if not gateway[CONF_DEVICES]:
        warnings.append("The PCT14 export contains no device this integration can use.")

    return [gateway], warnings


def yaml_to_config(content: str) -> tuple[list[dict], list[str]]:
    """`eltako:` yaml (or its content) -> gateway list (yaml structure)."""
    raw = yaml.safe_load(content) or {}
    if not isinstance(raw, dict):
        raise vol.Invalid("The file does not contain a yaml mapping.")
    section = raw.get(DOMAIN, raw)
    gateways = section.get(CONF_GATEWAY, []) or []
    if not gateways:
        raise vol.Invalid(f"No '{CONF_GATEWAY}:' list found in the file.")
    return [dict(g) for g in gateways], []


def parse_import(content: str) -> tuple[list[dict], list[str], str]:
    """Content of an uploaded file -> (gateways, warnings, detected format)."""
    if is_eodm(content):
        gateways, warnings = eodm_to_config(parse_eodm(content))
        return gateways, warnings, "eodm"
    if is_pct14(content):
        gateways, warnings = pct14_to_config(content)
        return gateways, warnings, "pct14"
    gateways, warnings = yaml_to_config(content)
    return gateways, warnings, "yaml"


### ---------------------------------------------------------------------------
### applying an import
### ---------------------------------------------------------------------------

def _gateway_identity(gateway: dict) -> tuple[str, str, str]:
    """Identity of a gateway for the import: device type + base id + name.

    Deliberately NOT the base id alone: several gateways can serve the same bus (e.g. a
    FAM14 and an FGW14-USB in the same rack) and devices can be taught into more than one
    gateway. Telegrams arriving through several gateways are fine and all commands are
    idempotent - so every gateway of the file is imported. The identity only prevents the
    same gateway from being created twice when the same file is imported again.
    """
    return (str(gateway.get(CONF_DEVICE_TYPE) or "").lower(),
            str(gateway.get(CONF_BASE_ID) or "00-00-00-00").upper(),
            str(gateway.get(CONF_NAME) or "").strip().casefold())


def _existing_gateways(hass: HomeAssistant) -> dict[tuple[str, str, str], dict]:
    """identity -> configured gateway (yaml and ui gateways alike)."""
    config = hass.data.get(DATA_ELTAKO, {}).get(ELTAKO_CONFIG, {}) or {}
    return {_gateway_identity(g): g for g in config.get(CONF_GATEWAY, []) or []}


def _plan(hass: HomeAssistant, gateways: list[dict], warnings: list[str]) -> dict:
    """What an import would do - shown to the user before applying."""
    existing = _existing_gateways(hass)
    plan = []
    for gateway in gateways:
        base_id = str(gateway.get(CONF_BASE_ID) or "").upper()
        devices = gateway.get(CONF_DEVICES, {}) or {}
        plan.append({
            "device_type": str(gateway.get(CONF_DEVICE_TYPE)),
            "base_id": base_id,
            "name": gateway.get(CONF_NAME) or "",
            "serial_path": gateway.get(CONF_SERIAL_PATH),
            "already_configured": _gateway_identity(gateway) in existing,
            "device_count": sum(len(entries or []) for entries in devices.values()),
            "devices_by_platform": {str(platform): len(entries or [])
                                    for platform, entries in devices.items()},
        })
    return {"gateways": plan, "warnings": warnings}


async def _add_missing_devices(hass: HomeAssistant, entry, devices: dict,
                               warnings: list[str]) -> tuple[int, int]:
    """Add every device which does not exist on the gateway yet. Returns (created, skipped).

    All devices of a gateway are stored in one go: every write of the options reloads the
    gateway, so adding them one by one would reload it once per imported device.
    """
    candidates = [(str(platform), device)
                  for platform, entries in devices.items() for device in entries or []]
    if not candidates:
        return 0, 0

    # "already configured/declared" is the merge working as intended - everything else
    # (broken address, unsupported eep) is worth a warning
    result = await device_config.async_add_ui_devices(hass, entry, candidates)
    for platform, address, message in result['errors']:
        warnings.append(f"{platform} '{address}': {message}")

    return len(result['added']), len(result['existing'])


async def async_apply_import(hass: HomeAssistant, gateways: list[dict],
                             warnings: list[str]) -> dict:
    """Store the gateways and devices like the web ui does (ui store / entry options).

    Every gateway of the file is imported - also several gateways on the same bus. A
    gateway which is already configured (same type, base id and name) is not created
    again, but its devices are still merged: missing ones are added to the existing
    gateway, existing ones are counted as skipped. Importing the same file twice
    therefore changes nothing, importing an extended file adds exactly the new parts.
    """
    created_gateways = 0
    created_devices = 0
    skipped_gateways = 0
    skipped_devices = 0

    existing = _existing_gateways(hass)
    config = hass.data.get(DATA_ELTAKO, {}).get(ELTAKO_CONFIG, {}) or {}

    for gateway in gateways:
        devices = gateway.pop(CONF_DEVICES, {}) or {}
        base_id = str(gateway.get(CONF_BASE_ID) or "").upper()

        identity = _gateway_identity(gateway)
        if identity in existing:
            skipped_gateways += 1
            configured = existing[identity]
            entry = device_config._find_gateway_entry(hass, int(configured.get(CONF_ID, -1)))
            if entry is None:
                warnings.append(f"Gateway '{gateway.get(CONF_NAME) or base_id}' is already "
                                f"configured but its config entry was not found - its devices "
                                f"were skipped.")
                continue
            added, existed = await _add_missing_devices(hass, entry, devices, warnings)
            created_devices += added
            skipped_devices += existed
            if added:
                warnings.append(f"Gateway '{gateway.get(CONF_NAME) or base_id}' already exists - "
                                f"{added} missing device(s) were added to it.")
            continue

        gateway[CONF_ID] = gateway_config.get_next_free_id(hass, config)
        if not gateway.get(CONF_SERIAL_PATH) and not gateway.get(CONF_GATEWAY_ADDRESS):
            # an .eodm file does not know the serial port of this machine
            gateway[CONF_SERIAL_PATH] = f"/dev/ttyUSB-imported-{gateway[CONF_ID]}"
            warnings.append(f"Gateway '{gateway.get(CONF_NAME) or base_id}': the file contains "
                            f"no serial port - placeholder '{gateway[CONF_SERIAL_PATH]}' was "
                            f"used, please correct it.")

        try:
            validated = await gateway_config.async_add_gateway(hass, gateway)
        except vol.Invalid as e:
            warnings.append(f"Gateway '{gateway.get(CONF_NAME) or base_id}': {e}")
            continue

        result = await hass.config_entries.flow.async_init(
            DOMAIN,
            context={"source": SOURCE_UI_GATEWAY},
            data={CONF_GATEWAY_DESCRIPTION: gateway_config.get_description(validated),
                  CONF_SERIAL_PATH: gateway_config.get_serial_path(validated)},
        )
        created_gateways += 1
        existing[identity] = validated

        if result.get("type") != "create_entry":
            warnings.append(f"Gateway '{gateway.get(CONF_NAME) or base_id}': config entry was "
                            f"not created ({result.get('reason')}) - devices were skipped.")
            continue

        entry = device_config._find_gateway_entry(hass, int(validated[CONF_ID]))
        if entry is None:
            warnings.append(f"Gateway '{gateway.get(CONF_NAME) or base_id}': cannot find its "
                            f"config entry - devices were skipped.")
            continue

        added, existed = await _add_missing_devices(hass, entry, devices, warnings)
        created_devices += added
        skipped_devices += existed

    LOGGER.info(f"[{LOG_PREFIX_IMPORT}] Imported {created_gateways} gateway(s) and "
                f"{created_devices} device(s) ({skipped_gateways} gateway(s) and "
                f"{skipped_devices} device(s) existed already), {len(warnings)} warning(s).")
    return {"created_gateways": created_gateways, "created_devices": created_devices,
            "skipped_gateways": skipped_gateways, "skipped_devices": skipped_devices,
            "warnings": warnings}


async def async_import(hass: HomeAssistant, content: str, dry_run: bool,
                       gateway_overrides: dict | None = None) -> dict:
    """Parse + plan or apply. Raises vol.Invalid/yaml.YAMLError on a broken file.

    gateway_overrides are merged into every imported gateway (e.g. the --demo
    flag of the standalone runtime disables auto_reconnect for its placeholder
    serial ports).
    """
    gateways, warnings, detected_format = parse_import(content)
    if gateway_overrides:
        for gateway in gateways:
            gateway.update(gateway_overrides)
    if dry_run:
        return {"format": detected_format, "dry_run": True, **_plan(hass, gateways, warnings)}
    result = await async_apply_import(hass, gateways, warnings)
    return {"format": detected_format, "dry_run": False, **result}


### ---------------------------------------------------------------------------
### websocket api
### ---------------------------------------------------------------------------

def register_websocket_commands(hass: HomeAssistant) -> None:
    websocket_api.async_register_command(hass, ws_config_import)


@websocket_api.require_admin
@websocket_api.websocket_command({
    vol.Required("type"): WS_CONFIG_IMPORT,
    vol.Required("content"): str,
    vol.Optional("dry_run", default=True): bool,
})
@websocket_api.async_response
async def ws_config_import(hass: HomeAssistant, connection, msg) -> None:
    try:
        result = await async_import(hass, msg["content"], msg["dry_run"])
    except (vol.Invalid, yaml.YAMLError) as e:
        connection.send_error(msg["id"], "invalid_file", str(e))
        return
    connection.send_result(msg["id"], result)
