alias: Dim Zigbee Light Up
description: ""
triggers:
  - trigger: event
    event_type: eltako.gw_1.btn_pressed.sid_FE-DB-0A-10.d_LT
conditions: []
actions:
  - repeat:
      while:
        - condition: state
          entity_id: binary_sensor.eltako_gw1_fe_db_0a_10
          state: "on"
      sequence:
        - target:
            entity_id: 2fb48f5d7e27ce6538b39bf718baa910
          data_template:
            brightness_step: 20
          action: light.turn_on
        - delay:
            milliseconds: 50
mode: single
